yandex_translation_service:
  url: "https://translate.api.cloud.yandex.net/translate/v2"
  api_key: "AQVNxX9MGQ2ocw-S65HitpkoXUqrYejglBYvZ_LB"
  api:
    translate: "/translate"
    translate_error: "error"

database:
  tables:
    translate_requests:
      columns:
        id: "id"
        date: "request_date"
        source: "source_language_code"
        target: "target_language_code"
        input: "input_text"
        output: "output_text"
        ip: "ip"
    word_translations:
      columns:
        id: "id"
        request_id: "request_id"
        word: "word"
        translated_word: "translated_word"


  queries:
    get_all: "SELECT * FROM translate_requests"
    get_translations: "SELECT * FROM word_translations WHERE request_id = ?"
    create: "INSERT INTO translate_requests(request_date, source_language_code, target_language_code, input_text, output_text, ip) values (?, ?, ?, ?, ?, ?)"
    create_translation: "INSERT INTO word_translations(request_id, word, translated_word) values (?, ?, ?)"